### ISSUE TITLE
Binary patch

### ISSUE THREAD

**Issue by cecekpawon** [RehabMan/EAPD-Codec-Commander#13]
Hello Rehabman, kudos for all of your hardworks!

Did you try binary patch solution to wake the sound after sleep instead with kext? (i [blogged](https://blog.thrsh.net/358-ekspedisi-el-capitan-1011-sound-awake.html.html) months ago with original link attached). I know this not an issue / completely  unrelated with this repo, sorry. Hope you found it working / useful for your next project :smile: (Tried without afail with smbios macpro6)

**Comment by RehabMan** [comment]
Thanks for the pointer... 

I tested it on my Lenovo u430: Added the patches to my config.plist, removed CodecCommander.kext. 

It does not work.  Audio is lost after sleep.

I may take a more detailed look at the patch to determine what it is trying to do in an effort to determine why people think this fixes the EAPD issue.
