### ISSUE TITLE
Not all audio devices wake after sleep

### ISSUE THREAD

**Issue by hameerabbasi** [RehabMan/EAPD-Codec-Commander#15]
[Read background in this related issue](https://github.com/vit9696/AppleALC/issues/77)

It seems Codec Commander only wakes up the devices already listed in System Preferences > Sound. So, for example, with autodetect enabled (as in that issue), if the headphones are plugged in, only those work after sleep and if speakers are plugged in, only those work after sleep.

Seems to be related to [this issue for the ALC292](https://github.com/RehabMan/EAPD-Codec-Commander/commit/99d23400e7ba4c0eee6c92fdaff51ba5a061e6a0#diff-e9fb920e07540e904f97197a0a378f84). Maybe the same command will work?

**Comment by RehabMan** [comment]
CodecCommander sets EAPD for all nodes that report EAPD.
