### ISSUE TITLE
ALC255 Awaken silence

### ISSUE THREAD

**Issue by dgtutu** [RehabMan/EAPD-Codec-Commander#18]
Hi，
My voice if I don't use Codecommander only single track with bad tone quality.
But sleep after awakening will not be able to play a sound only I pull out and insert the Earphone plug agiain,Can you tell me how should I do, my codec sense has something worng:
Codec.txt
ALC 255
thank you !

**Comment by RehabMan** [comment]
Probably a mistake in your AppleHDA patching...
