### ISSUE TITLE
How to customize the SSDT for your own codec

### ISSUE THREAD

**Issue by sandyplus** [RehabMan/EAPD-Codec-Commander#20]
Dear RehabMan,
Your CodecCommander works great most of the time.
However, sometimes the voice disordered after reboot.
I guess something is wrong with the default codec value, and I want to customize it for my own codec value. 
I have dumped the related codec information from ubuntu. However, I have no idea what to do next. Would you mind give me some suggestions/clues?
Thank you for your help.

**Comment by RehabMan** [comment]
You will need to read the Intel HDA specification.
And read up on AppleHDA patching.
