### ISSUE TITLE
Not working with 1150 on GA-H170N-WIFI and GA-Z170N-WIFI

### ISSUE THREAD

**Issue by dmatora** [RehabMan/EAPD-Codec-Commander#23]
Not sure about desktop boards but there are defiantly using EAPD

Those who straggle with getting it working, can get it fixed with updating Info.plist in 1150 section,  Update Nodes from false to true

Unlike the other version of Codec-Commander, that works with 1150 out of the box, but only works from S/L/E, this version, once patched, works from Clover/kext/Others

**Comment by RehabMan** [comment]
The ALC1150 is configured for desktop boards (EAPD not common).

It is easy to override any Info.plist setting.

For example, overriding Update Nodes:
```
DefinitionBlock ("", "SSDT", 1, "hack", "CC-over", 0)
{
    Name(_SB.PCI0.HDEF.RMCF, Package()
    {
        "CodecCommander", Package()
        {
            "UpdateNodes", ">y",
        },
    })
}
//EOF
```
